data:
  batch_size: 16
  crop_size:
  - 90  # 行数
  - 116 # 列数
  num_workers: 4
  pin_mem: true
  data_dir: "/home/chentingyu/BrainDiagnostics/demo/ROISignals_FunImgARCWF"  # MDD数据集路径

logging:
  folder: logs/mdd_classification
  write_tag: mdd

mask:
  allow_overlap: false
  patch_size: 8
  min_keep: 2
  enc_mask_scale:
  - 0.84
  - 1
  pred_mask_R_scale:
  - 0.45
  - 0.6
  pred_mask_T_roi_scale:
  - 0.2
  - 0.6
  pred_mask_R_roi_scale:
  - 0.15
  - 0.3
  pred_mask_T_scale:
  - 0.0
  - 0.4

meta:
  load_checkpoint: false
  model_name: vit_base
  pred_depth: 4
  pred_emb_dim: 256
  read_checkpoint: null
  use_bfloat16: false  # CUDA 11.6可能不支持bfloat16
  accumulation_steps: 2
  attn_mode: normal  # CUDA 11.6可能不支持flash_attn
  add_w: mapping
  downsample: true
  mask_mode: 'roi_mask'
  use_standatdization: true
  num_classes: 2  # MDD分类任务（2个类别）

optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 50  # 增加训练轮数
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0001
  warmup: 5
  weight_decay: 0.04 